### PR TITLE
Force C/C++ code to be formatted by GitHub Actions

### PR DESCRIPTION
**Pull request by alexreinking**
Trying to dip our toes into automatic formatting. This new workflow will automatically run `clang-format` on all our C/C++ files and commit the result to the PR. Later, we can add Python autoformatting to this workflow.

### CODE REVIEW

**Comment by yamaguchi1024** [comment]
Also, if CI does not trigger CI when linting the code, do we always need to trigger CI by pushing empty commit after formatting?

**Comment by alexreinking** [comment]
> Does clang-format apply to new C files as well?

Yes, it applies to the whole repository except `dependencies/` and `tests/gemmini/gemmini-rocc-tests/` (i.e. third party code modulo small patches).

> Also, if CI does not trigger CI when linting the code, do we always need to trigger CI by pushing empty commit after formatting?

Yes, but that's not a problem. The alternative is to error when the code is improperly formatted, but then you have to do the work of running clang-format and pushing that, anyway. If the code is properly formatted to begin with, no new commits will be created. So no matter what, if the code is improperly formatted, then you will need to push _something_ (either an empty commit or a fix commit). This way is just less work (`git commit --allow-empty -m "trigger gha"`).

**Comment by yamaguchi1024** [comment]
Is it not possible to trigger CI automatically after formatting? (no worries if that's difficult)

**Comment by alexreinking** [comment]
> Is it not possible to trigger CI automatically after formatting? (no worries if that's difficult)

It is potentially dangerous if a bug in clang-format is non-idempotent on a source file.

**Review by yamaguchi1024 — APPROVED** [review]

**Pull request merged**
